app/app/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='static_pages/index.html'), name='index'),
    url(r'^auction/', include('auction.urls', namespace='auction')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^auc_accounts/', include('auc_accounts.urls', namespace='auc_accounts')),
    url(r'^forums/', include('forums.urls', namespace='forums')),
    url(r'^admin/', include(admin.site.urls)),
    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='static_pages/about.html'), name='about'),
    url(r'^services/$', TemplateView.as_view(template_name='static_pages/services.html'), name='services'),
    url(r'^partners/$', TemplateView.as_view(template_name='static_pages/partners.html'), name='partners'),
    url(r'^bankruptcy/$', TemplateView.as_view(template_name='static_pages/bankruptcy.html'), name='bankruptcy'),
    url(r'^analitic/$', TemplateView.as_view(template_name='static_pages/analitic.html'), name='analitic'),
    url(r'^contacts/$', TemplateView.as_view(template_name='static_pages/contacts.html'), name='contacts'),
    url(r'^rules/$', TemplateView.as_view(template_name='static_pages/rules.html'), name='rules'),
    url(r'^price/$', TemplateView.as_view(template_name='static_pages/price.html'), name='price'),
    url(r'^secretary/$', TemplateView.as_view(template_name='static_pages/secretary.html'), name='secretary'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/auc_accounts/urls.py
from django.conf.urls import patterns, url
from auc_accounts.views import login_user, logout_user, user_profile, send_sms_ajax, verify_phone, order, create_order, \
    cb_callback, cb_error, cb_success
from django.views.generic import TemplateView

urlpatterns = patterns(
        '',
        url(r'^success/', TemplateView.as_view(template_name='auc_accounts/success.html'), name='success'),
        url(r'^login/', login_user, name='login'),
        url(r'^logout/', logout_user, name='logout'),
        url(r'^profile/', user_profile, name='profile'),
        url(r'^send_sms_ajax/(?P<user_id>\d+)/$', send_sms_ajax, name='send_sms_ajax'),
        url(r'^verify_phone/$', verify_phone, name='verify_phone'),
        url(r'^order/(?P<order_id>\d+)/$', order, name='order'),
        url(r'^create_order/$', create_order, name='create_order'),
        url(r'^cb_callback/$', cb_callback, name='cb_callback'),
        url(r'^cb_success/$', cb_success, name='cb_success'),
        url(r'^cb_error/$', cb_error, name='cb_error'),
)

app/auc_accounts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.utils import timezone


class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, verbose_name=_('user'))
    email_subscribe = models.BooleanField(default=False, blank=True, verbose_name=_('email subscribe'))
    organization = models.BooleanField(default=False, blank=True, verbose_name=_('organization'))
    phone = models.CharField(max_length=200, verbose_name=_('phone'))
    city = models.CharField(max_length=200, verbose_name=_('city'), default='')
    ogrn = models.CharField(max_length=200, verbose_name=_('OGRN'), default='')
    premium_expiration_date = models.DateTimeField(default=timezone.now, verbose_name=_('Premium expiration date'))
    verified = models.BooleanField(default=False, blank=True, verbose_name=_('verified'))
    sms_token = models.IntegerField(verbose_name=_('sms token'), default=0)

    def is_premium(self):
        return self.verified and self.premium_expiration_date > timezone.now()

    def __str__(self):
        return self.user.username


class Order(models.Model):
    user = models.ForeignKey(User)
    create_date = models.DateTimeField(default=timezone.now, verbose_name=_('Order create date'))
    purchase_date = models.DateTimeField(null=True, default=None, verbose_name=_('Order purchase date'))
    price = models.IntegerField(verbose_name=_('price'), default=0)
    status = models.BooleanField(default=False, blank=True, verbose_name=_('purchased'))
    months = models.IntegerField(verbose_name=_('period'), default=0)

    def __str__(self):
        return '{} {}'.format(self.user.username, self.price)


class CbRequest(models.Model):
    request = models.TextField()
    create_date = models.DateTimeField(default=timezone.now, verbose_name=_('Order create date'))

    def __str__(self):
        return str(self.create_date)

app/auc_accounts/forms.py
from django import forms
from django.conf import settings
from auc_accounts.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.utils.translation import ugettext_lazy as _
from registration.forms import RegistrationFormUniqueEmail
from datetime import datetime, timedelta
import re


class UserProfileRegistrationForm(RegistrationFormUniqueEmail):
    organization = forms.BooleanField(label=_('As organization?'), initial=False, required=False)
    phone = forms.CharField(max_length=100, label=_('phone'))
    city = forms.CharField(max_length=100, label=_('city'))
    ogrn = forms.CharField(max_length=100, label=_('OGRN'), required=False)

    class Meta:
        model = User
        fields = ('organization', 'first_name', 'ogrn', 'last_name', 'email')

    def clean_ogrn(self):
        if self.cleaned_data['organization'] and not self.cleaned_data['ogrn']:
            raise forms.ValidationError(_("This field is required."))
        return self.cleaned_data['ogrn']

    def save(self, commit=True):
        user = super(UserProfileRegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data['email']
        user.save()
        user_profile = UserProfile()
        user_profile.user = user
        user_profile.phone = self.cleaned_data['phone']
        user_profile.city = self.cleaned_data['city']
        if self.cleaned_data['organization']:
            user_profile.organization = True
            user_profile.ogrn = self.cleaned_data['ogrn']
            user_profile.premium_expiration_date = datetime.now() + timedelta(days=settings.TEST_PREMIUM_DAYS)
        user_profile.save()
        return user


class UserProfileForm(forms.Form):
    email_subscribe = forms.BooleanField(label=_('email subscribe'), initial=True, required=False)
    first_name = forms.CharField(max_length=100, label=_('first name'))
    last_name = forms.CharField(max_length=100, label=_('last name'), required=False)
    email = forms.EmailField(label=_('email'))
    phone = forms.CharField(max_length=20, label=_('phone'))
    ogrn = forms.CharField(max_length=20, label=_('ogrn'), required=False)
    city = forms.CharField(max_length=20, label=_('city'))
    password = forms.CharField(max_length=20, required=False, label=_('password'))
    password1 = forms.CharField(max_length=20, required=False, label=_('new password'))
    password2 = forms.CharField(max_length=20, required=False, label=_('repeat password'))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(UserProfileForm, self).__init__(*args, **kwargs)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 != password2:
            raise forms.ValidationError(_('Your passwords do not match'))
        return password2

    def clean_password(self):
        if not self.cleaned_data.get('password'):
            return False
        if not authenticate(username=self.user.username, password=self.cleaned_data.get('password')):
            raise forms.ValidationError(_('Wrong password'))

    def clean_phone(self):
        if not self.cleaned_data.get('phone'):
            raise forms.ValidationError(_("This field is required."))
        return '+{}'.format(re.sub("[^0-9]", "", self.cleaned_data.get('phone')))

    def save(self):
        user = User.objects.get(pk=self.user.id)
        profile = UserProfile.objects.get(pk=self.user)
        profile.email_subscribe = self.cleaned_data.get('email_subscribe')
        if not profile.phone or profile.organization:
            profile.phone = self.cleaned_data.get('phone')
        profile.city = self.cleaned_data.get('city')
        user.email = self.cleaned_data.get('email')
        user.username = self.cleaned_data.get('email')
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        if self.cleaned_data.get('password1'):
            user.set_password(self.cleaned_data.get('password1'))

        user.save()
        profile.save()

app/auc_accounts/views.py
from django.shortcuts import render_to_response, render
from django.template.context_processors import csrf
from auc_accounts.forms import UserProfileForm
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, authenticate, login
from django.utils.translation import ugettext_lazy as _
from django.template import RequestContext
from auc_accounts.models import UserProfile, Order, CbRequest
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta
from django.conf import settings
import json
import random
import re
import requests
import hashlib
from decimal import Decimal
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone


def login_user(request):
    logout(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user and user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('index'))
    return render_to_response('auc_accounts/login.html', context_instance=RequestContext(request))


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


@login_required
def user_profile(request):
    profile, created = UserProfile.objects.get_or_create(user=request.user)
    form = None

    if request.method == 'POST':
        form = UserProfileForm(request.user, request.POST)
        if form.is_valid() and form.has_changed():
            form.save()
            return HttpResponseRedirect(reverse('auc_accounts:profile'))
    context = {
        'user_name': '{} {}'.format(request.user.first_name, request.user.last_name),
        'phone': profile.phone,
        'email': request.user.email,
        'orders': Order.objects.filter(user=request.user, status=False)
    }
    context.update(csrf(request))
    if form:
        context['form'] = form
    else:
        context['form'] = UserProfileForm(request.user, initial={
            'email_subscribe': profile.email_subscribe,
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'email': request.user.email,
            'phone': profile.phone,
            'city': profile.city,
            'ogrn': profile.ogrn,
        })
    return render(request, 'auc_accounts/profile.html', context)


def _send_sms(to, text):
    url = 'http://sms.ru/sms/send'
    params = {
        'api_id': settings.SMS_RU_KEY,
        'to': to,
        'text': text,
        'from': settings.SMS_RU_SENDER
    }
    if settings.DEBUG:
        params['test'] = 1

    r = requests.get(url, params=params)
    return r


@login_required
def send_sms_ajax(request, user_id):
    profile = UserProfile.objects.get(user_id=user_id)
    profile.sms_token = random.randint(1000, 9999)
    profile.phone = '+{}'.format(re.sub("[^0-9]", "", profile.phone))
    profile.save()
    res = _send_sms(profile.phone, profile.sms_token)
    result = {'success': False, 'message': res.text,}
    if res.text.startswith('100'):
        result['success'] = True

    return HttpResponse(json.dumps(result), content_type='application/json')


@login_required
def verify_phone(request):
    if request.user.userprofile.sms_token == int(request.POST.get('sms_code')):
        request.user.userprofile.verified = True
        request.user.userprofile.premium_expiration_date += timedelta(days=settings.TEST_PREMIUM_DAYS)
        request.user.userprofile.save()
    return HttpResponseRedirect(reverse('auc_accounts:profile'))


@login_required
def order(request, order_id):
    order = Order.objects.get(pk=order_id)
    product_id = settings.CHRONOPAY_PRODUCT_ID
    sharedsec = settings.CHRONOPAY_SHARED_SEC
    context = {
        'product_id': product_id,
        'sign': hashlib.md5('{}-{}-{}'.format(product_id, order.price, sharedsec).encode()).hexdigest(),
        'order': order,
    }
    return render(request, 'auc_accounts/order.html', context)


@login_required
def create_order(request):
    if request.method != 'POST':
        raise Http404
    months = int(request.POST.get('months'))
    price_per_month = 400
    if months >= 3:
        price_per_month = 350
    if months == 12:
        price = 4200
    else:
        price = price_per_month * months
    order = Order.objects.create(
            user=request.user,
            price=price,
            months=months,
    )
    return HttpResponseRedirect(reverse('auc_accounts:order', kwargs={'order_id': order.id}))


@csrf_exempt
def cb_callback(request):
    request_json = json.dumps({
        'GET': repr(request.GET),
        'POST': repr(request.POST),
        'META': repr(request.META),
    })
    CbRequest.objects.create(request=request_json)

    if request.META.get('REMOTE_ADDR') != settings.CHRONOPAY_REMOTE_IP:
        raise Http404

    sign = hashlib.md5('{}{}{}{}{}'.format(
            settings.CHRONOPAY_SHARED_SEC,
            request.POST.get('customer_id'),
            request.POST.get('transaction_id'),
            request.POST.get('transaction_type'),
            request.POST.get('total'),
    ).encode()).hexdigest()

    if sign != request.POST.get('sign'):
        raise Http404

    order = Order.objects.get(id=request.POST.get('cs1'))
    order.status = True
    order.purchase_date = timezone.now()
    order.save()
    if order.user.userprofile.premium_expiration_date < timezone.now():
        order.user.userprofile.premium_expiration_date = timezone.now()

    order.user.userprofile.premium_expiration_date += timedelta(order.months * 30)

    order.user.userprofile.save()

    return HttpResponse(json.dumps({'result': 'OK'}), content_type='application/json')


@csrf_exempt
def cb_success(request):
    return render(request, 'auc_accounts/cb_success.html')


@csrf_exempt
def cb_error(request):
    return render(request, 'auc_accounts/cb_error.html')

app/auc_accounts/templates/auc_accounts/cb_error.html
{% extends "layout.html" %}

{% block content %}
<div class="auc_accounts__error">
  <h1>Произошла ошибка оплаты</h1>
  Что-то пошло не так, обратитесь, пожалуйста, в техническую поддержку.
</div>
{% endblock %}

app/auc_accounts/templates/auc_accounts/cb_success.html
{% extends "layout.html" %}

{% block content %}
<div class="auc_accounts__success">
  <h1>Успешная активация премиум</h1>
  Поздравляем! Вы теперь имеете доступ к премиум функционалу сайта.
  <p>Подписка будет активирована как только мы получим подтверждение от платежной системы.</p>

</div>
{% endblock %}

app/auc_accounts/templates/auc_accounts/login.html
{% extends "layout.html" %}

{% block content %}
  <form class="form-horizontal" name="LoginForm" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label class="control-label col-sm-2" for="username">Email</label>

      <div class="col-sm-6">
        <input type="text" id="username" name="username" class="form-control">
      </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2" for="password">Password</label>

      <div class="col-sm-6">
        <input type="password" name="password" id="password" class="form-control">
      </div>
    </div>
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-success">Login</button>
    </div>
  </div>
  </form>
{% endblock %}

app/auc_accounts/templates/auc_accounts/order.html
{% extends "layout.html" %}
{% load widget_tweaks staticfiles %}

{% block content %}
<div class="auc_accounts__purchase">
  <h1>Покупка премиум</h1>
  <p>Ваш заказ на сумму {{ order.price }}р. готов к оплате.</p>
  <p>После оплаты Ваш премиум доступ продлится на {{ order.months }} мес.</p>

  <form action="https://payments.chronopay.com/" method="POST">
    <input type="hidden" name="product_id" value="{{ product_id }}"/>
    <input type="hidden" name="product_price" value="{{ order.price }}"/>
    <input type="hidden" name="cs1" value="{{ order.id }}" />
    <input type="hidden" name="cb_url" value="http://{{ request.get_host }}{% url 'auc_accounts:cb_callback' %}"/>
    <input type="hidden" name="success_url" value="http://{{ request.get_host }}{% url 'auc_accounts:cb_success' %}"/>
    <input type="hidden" name="decline_url" value="http://{{ request.get_host }}{% url 'auc_accounts:cb_error' %}"/>
    <input type="hidden" name="sign" value="{{ sign }}"/>
    <input type="submit" value="Оплатить"/>
  </form>
</div>
{% endblock %}

app/auc_accounts/templates/auc_accounts/profile.html
{% extends "layout.html" %}

{% load widget_tweaks %}
{% load staticfiles %}
{% block content %}
<div class="auc_accounts__profile">
  <div class="form-header clearfix">Личный кабинет
    {% if user.userprofile.organization %}(организация){% else %}(физ лицо){% endif %}
  </div>
  <div class="cabinet col-sm-*">
    <div class="row">
      <div class="col-sm-6">
        <div class="col-sm-2">
          <img src="{% static 'img/user_photo.png' %}">
        </div>
        <div class="name col-sm-10">
          <p>{{ user_name }}</p>
        </div>
        <div class="col-sm-2">
          <img src="{% static 'img/phone.png' %}">
        </div>
        <div class="phone col-sm-10">
          <p>{{ phone }}
            {% if not user.userprofile.organization and not user.userprofile.verified %}
            <a href="#" class="send_sms" data-user="{{ user.id }}">подтвердить</a> <br>
            <span>Подтвердите Ваш номер телефона, чтобы получить демо доступ на 15 дней.</span>
          <form action="{% url 'auc_accounts:verify_phone' %}" method="post" class="send-form">
            {% csrf_token %}
            <input type="text" name="sms_code">
            <input type="submit" value="OK">
          </form>
          {% elif not user.userprofile.organization %}
          <i class="fa fa-check-square-o"></i>
          {% endif %}
          </p>
        </div>
        <div class="col-sm-2">
          <img src="{% static 'img/mail.png' %}" height="12" width="19">
        </div>
        <div class="mail col-sm-10">
          <p>{{ email }}</p>
        </div>
      </div>
      <div class="col-sm-6">

        {% if user.userprofile.is_premium %}
        <div class="col-sm-2">
          <i class="fa fa-money fa-2x default-label-margin"></i>
        </div>
        <div class="name col-sm-10">
          <p>Премиум подписка до {{ user.userprofile.premium_expiration_date }}</p>
        </div>
        {% else %}
        <div class="col-sm-2">
          <i class="fa fa-usd fa-2x default-label-margin"></i>
        </div>
        <div class="name col-sm-10">
          <h1>Покупка премиум</h1>
          <ul>
            {% for order in orders %}
              <li><a href="{% url 'auc_accounts:order' order.id %}">Заказ на срок {{ order.months }} мес.</a></li>
            {% endfor %}
          </ul>

          <form action="{% url 'auc_accounts:create_order' %}" method="post">
            {% csrf_token %}
            <div class="form-group clearfix">
              <label for="months" class="control-label">Период (месяцев):</label>
              <select name="months" id="months">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
              </select>
            </div>
            <input type="submit" value="Сделать заказ">
          </form>
        </div>
        {% endif %}
      </div>
    </div>
    <form action="{% url 'auc_accounts:profile' %}" method="post">
      {% csrf_token %}
      <div class="form-group clearfix">
        <div class="col-sm-6">
          <div class="checkbox">
            {{ form.email_subscribe }}
            <label>
              Получать новостную расслыку на e-mail
            </label>
          </div>
        </div>
      </div>
      <hr>
      <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
        <div class="panel panel-default">
          <div class="panel-heading" role="tab" id="headingOne">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                 aria-expanded="true" aria-controls="collapseOne">
                Изменение данных
              </a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse" role="tabpanel"
               aria-labelledby="headingOne">
            <div class="panel-body">
              <div class="form-group clearfix">
                <label for="filter_name" class="col-sm-3 control-label">
                  {% if user.userprofile.organization %}Название:{% else %}Ваше имя:{% endif %}
                </label>
                {{ form.first_name.errors }}
                <div class="col-sm-6">
                  {{ form.first_name|add_class:'form-control' }}
                </div>
              </div>
              {% if user.userprofile.organization %}
              <div class="form-group clearfix">
                <label for="filter_name" class="col-sm-3 control-label">ИНН:</label>
                {{ form.ogrn.errors }}
                <div class="col-sm-6">
                  {{ form.ogrn|add_class:'form-control'|attr:"disabled" }}
                </div>
              </div>
              {% else %}
              <div class="form-group clearfix">
                <label for="filter_name" class="col-sm-3 control-label">Фамилия:</label>
                {{ form.last_name.errors }}
                <div class="col-sm-6">
                  {{ form.last_name|add_class:'form-control' }}
                </div>
              </div>
              {% endif %}
              <div class="form-group clearfix">
                <label for="filter_name" class="col-sm-3 control-label">E-mail:</label>
                {{ form.email.errors }}
                <div class="col-sm-6">
                  {{ form.email|add_class:'form-control' }}
                </div>
              </div>
              <div class="form-group clearfix">
                <label for="filter_name" class="col-sm-3 control-label">Телефон:</label>
                {{ form.phone.errors }}
                <div class="col-sm-6">
                  {{ form.phone|add_class:'form-control' }}
                </div>
              </div>
              <div class="form-group clearfix">
                <label for="filter_name" class="col-sm-3 control-label">Город:</label>
                {{ form.city.errors }}
                <div class="col-sm-6">
                  {{ form.city|add_class:'form-control' }}
                </div>
              </div>
              <br>

              <div class="col-sm-*">
                <h4>Сменить пароль</h4></div>
              <div class="form-group clearfix">
                <label for="filter_name" class="col-sm-3 control-label">Старый пароль:</label>
                {{ form.password.errors }}
                <div class="col-sm-6">
                  {% render_field form.password type='password' class='form-control' %}
                </div>
              </div>
              <div class="form-group clearfix">
                <label for="filter_name" class="col-sm-3 control-label">Новый пароль:</label>
                {{ form.password1.errors }}
                <div class="col-sm-6">
                  {% render_field form.password1 type='password' class='form-control' %}
                </div>
              </div>
              <div class="form-group clearfix">
                <label for="filter_name" class="col-sm-3 control-label">Подтвердите новый
                  пароль:</label>
                {{ form.password2.errors }}
                <div class="col-sm-6">
                  {% render_field form.password2 type='password' class='form-control' %}
                </div>
              </div>
              <div class="col-sm-4">
                <button type="submit" class="btn btn-success btn-lg">Сохранить изменения</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/auc_accounts/templates/auc_accounts/register.html
{% extends "layout.html" %}
{% load widget_tweaks %}

{% block head-title %}
Форма регистрации на сайте торгов по банкротству в Москве
{% endblock %}

{% block head-description %}
Заполните форму онлайн регистрации сайта электронных торгов в Москве. Предоставляем доступ к аукционам,
площадкам по банкротству, помощь в покупках с аукционов по банкротству и др.- можно заполнив форму обратной связи.
Интернет-проект Банк-Лот. Тел. +7 499 899 05 05
{% endblock %}

{% block content %}
<form action="{% url 'auc_accounts:registration' %}" method="post" class="registration_form">
  {% csrf_token %}
  {% for field in form %}
  <div class="form-group clearfix{% if field.errors %} has-error{% endif %}">
    <label class="col-sm-3 control-label">{{ field.label_tag }}</label>
    <div class="col-sm-6">
      {{ field|add_class:'form-control' }}
      {% for error in field.errors %}
      <p class="help-block errorlist">{{ error }}</p>
      {% endfor %}
    </div>
  </div>
  {% endfor %}
  <div class="col-sm-6">
    <p><a href="{% url 'rules' %}">Пользовательское соглашение</a></p>
    <div class="checkbox">
      <label>
        <input class="check_me" type="checkbox" value="">
        Прочитал(а) и сгласен(а) <span>*</span>
      </label>
    </div>
    <input class="btn btn-success disabled" type="submit" value="Зарегестрироваться"/>
  </div>
</form>
{% endblock %}

app/auc_accounts/templates/auc_accounts/success.html
{% extends "layout.html" %}

{% block content %}
  Благодарим за регистрацию. Вы можете зайти на сайт и воспользоваться дополнительным функционалом.
{% endblock %}