app/app/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='static_pages/index.html'), name='index'),
    url(r'^auction/', include('auction.urls', namespace='auction')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^auc_accounts/', include('auc_accounts.urls', namespace='auc_accounts')),
    url(r'^forums/', include('forums.urls', namespace='forums')),
    url(r'^admin/', include(admin.site.urls)),
    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='static_pages/about.html'), name='about'),
    url(r'^services/$', TemplateView.as_view(template_name='static_pages/services.html'), name='services'),
    url(r'^partners/$', TemplateView.as_view(template_name='static_pages/partners.html'), name='partners'),
    url(r'^bankruptcy/$', TemplateView.as_view(template_name='static_pages/bankruptcy.html'), name='bankruptcy'),
    url(r'^analitic/$', TemplateView.as_view(template_name='static_pages/analitic.html'), name='analitic'),
    url(r'^contacts/$', TemplateView.as_view(template_name='static_pages/contacts.html'), name='contacts'),
    url(r'^rules/$', TemplateView.as_view(template_name='static_pages/rules.html'), name='rules'),
    url(r'^price/$', TemplateView.as_view(template_name='static_pages/price.html'), name='price'),
    url(r'^secretary/$', TemplateView.as_view(template_name='static_pages/secretary.html'), name='secretary'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/auction/urls.py
from django.conf.urls import patterns, url
from auction.views import *

urlpatterns = patterns(
    '',
    url(r'^$', lot_list, name='lot_list'),
    url(r'^favorite/(?P<id>\d+)/$', favorite_list, name='favorite_list'),
    url(r'^favorite/$', favorite_list, name='favorite_list'),
    url(r'^(?P<pk>\d+)/$', lot_details, name='lot_details'),
    url(r'^mark_read/(?P<lot_id>\d+)/$', toggle_lot_read_ajax, name='mark_read'),
    url(r'^read_all/$', read_all, name='read_all'),
    url(r'^add_chapter$', add_chapter, name='add_chapter'),
    url(r'^del_chapter/(?P<id>\d+)$', del_chapter, name='del_chapter'),
    url(r'^get_comment/(?P<lot_id>\d+)/$', get_comment, name='get_comment'),
    url(r'^set_comment/(?P<lot_id>\d+)/$', set_comment, name='set_comment'),
    url(r'^add_to_chapter/$', add_to_chapter, name='add_to_chapter'),
    url(r'^remove_from_chapter/$', remove_from_chapter, name='remove_from_chapter'),
    url(r'^calendar/$', calendar, name='calendar'),
    url(r'^data_by_month/(?P<year>\d+)/(?P<month>\d+)/$', data_by_month, name='data_by_month'),
    url(r'^monitoring/$', monitoring, name='monitoring'),
    url(r'^monitoring/filter/$', filter_edit, name='filter_add'),
    url(r'^monitoring/filter/(?P<filter_id>\d+)/$', filter_edit, name='filter_edit'),
    url(r'^question/$', question_form, name='question_form'),

    # blog
    url(r'^blog/$', blog, name='blog'),
    url(r'^blog/blog_theme$', blog_theme, name='blog_theme'),
    url(r'^blog/blog_theme/blog_question$', blog_question, name='blog_question'),
)

app/forums/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from forums.views import CategoryListView, ForumDetailView, TopicDetailView, TopicCreateView, PostCreateView


urlpatterns = patterns('',
    url(r'^$', CategoryListView.as_view(), name='overview'),
    url(r'^(?P<pk>\d+)/$', ForumDetailView.as_view(), name='forum'),
    url(r'^(?P<forum_id>\d+)/create/$', login_required(TopicCreateView.as_view()), name='topic_create'),
    url(r'^topic/(?P<pk>\d+)/$', TopicDetailView.as_view(), name='topic'),
    url(r'^topic/(?P<pk>\d+)/create/$', login_required(PostCreateView.as_view()), name='post_create'),
)

app/app/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
  <meta charset="UTF-8">
  <title>
    {% block head-title %}
    Торги по банкротству – поиск лотов, сопровождение сделок. г. Москва, тел. +7 (499) 899-05-05
    {% endblock %}
  </title>
  <meta name="description" content="{% block head-description %}
    Банк-Лот – система поиска лотов на аукционах по банкротству. Поможем принять участие в торгах по банкротству,
    от получения ЭЦП до оформления всех необходимых документов. г. Москва, тел. +7 (499) 899-05-05
    {% endblock %}"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
</head>

<body>
<div class="wrapper {% if user.is_authenticated %} logged-in {% else %} not-logged-in {% endif %}">
  <div class="navbar navbar-static-top navbar-inverse main-nav" role="navigation">
    <div class="container">
      <div class="navbar-header pull-left">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'index' %}"><b>БАНК-ЛОТ</b></a>
      </div>

      <div class="navbar-right nav header-auth {% if user.is_authenticated %} is-sign-in{% endif %}">
        {% if user.is_authenticated %}
        <a href="{% url 'auth_logout' %}" class="header-auth__item header-auth__item--fa">
          <i class="fa fa-sign-out fa-2x"></i>
        </a>
        <a href="/auc_accounts/profile" class="header-auth__item">
            <span class="btn-reg">
              {% if user.first_name %}
                {{ user.first_name }}
              {% else %}
                {{ user.username }}
              {% endif %}
            </span>
        </a>
        {% else %}
        <a href="{% url 'auth_login' %}" class="header-auth__item header-auth__item--fa">
          <i class="fa fa-sign-in fa-2x"></i>
        </a>
        <a href="{% url 'registration_register' %}" class="header-auth__item">
          <span class="btn-reg">Регистрация</span>
        </a>
        {% endif %}
      </div>

      <div class="collapse navbar-collapse navbar-left main-menu">
        <ul class="nav navbar-nav">
          <li class="{% if request.path == '/auction' %} active {% endif %} main-menu__item">
            <a href="{% url 'auction:lot_list' %}">
              Торги
            </a>
          </li>
          <li class="{% if request.path == '/services' %} active {% endif %} main-menu__item">
            <a href="{% url 'services' %}">
              Услуги
            </a>
          </li>
          <!--<li class="{% if request.path == '/price' %} active {% endif %} main-menu__item">-->
            <!--<a href="{% url 'price' %}">-->
              <!--Тарифы-->
            <!--</a>-->
          <!--</li>-->
          <li class="{% if request.path == '/partners' %} active {% endif %} main-menu__item">
            <a href="{% url 'partners' %}">
              Партнеры
            </a>
          </li>
          <li class="{% if request.path == '/forums' %} active {% endif %} main-menu__item">
            <a href="{% url 'forums:overview' %}">
              Форумы
            </a>
          </li>
          <li class="{% if request.path == '/contacts' %} active {% endif %} main-menu__item">
            <a href="{% url 'contacts' %}">
              Контакты
            </a>
          </li>
        </ul>
      </div>


    </div>

  </div>

  <main class="content">
    {% block layout %}
    Reload me
    {% endblock %}
  </main>

</div>

<footer class="clearfix footer" id="footer">
  <div class="container">
    <p class="col-xs-12 col-sm-4 col-md-3"><img src="http://placehold.it/200x40">
      <img src="http://placehold.it/40x40"></p>

    <div class="clearfix col-xs-12 col-lg-offset-1 col-md-5 col-sm-8 text-left ">
      <ul class="list-unstyled">
        <!--<li {% if request.path == '/about' %} class="active" {% endif %}>-->
          <!--<a href="{% url 'about' %}">-->
            <!--О проекте-->
          <!--</a>-->
        <!--</li>-->
        <li {% if request.path == '/services' %} class="active" {% endif %}>
          <a href="{% url 'services' %}">
            Услуги
          </a>
        </li>
        <li {% if request.path == '/price' %} class="active" {% endif %}>
          <a href="{% url 'price' %}">
            Тарифы
          </a>
        </li>
        <li {% if request.path == '/contacts' %} class="active" {% endif %}>
        <a href="{% url 'contacts' %}">
          Контакты
        </a>
        </li>
        <li {% if request.path == '/partners' %} class="active" {% endif %}>
        <a href="{% url 'partners' %}">
          Партнеры
        </a>
        </li>
      </ul>

      <div class="footer__links">
        <p class="footer__links__item"><a href="{% url 'rules' %}">
          Правила и политика использования сайта
        </a></p>
      </div>

    </div>
    <p class="col-xs-12 col-md-offset-0 col-md-3 footer__meta">
      <span class="text-muted footer__meta__item">Email тех. поддержки</span>
      <span class="footer__meta__item"><a href="mailto:support@banklot.ru">support@banklot.ru</a></span>
      <span class="text-muted footer__meta__item">
        Электронная почта
      </span>
        <span class="footer__meta__item">
        <a href="mailto:vashlot@mail.ru">vashlot@mail.ru</a>
      </span>
      <span>
        <!-- Yandex.Metrika informer -->
        <a href="https://metrika.yandex.ru/stat/?id=33823419&amp;from=informer"
        target="_blank" rel="nofollow"><img src="https://informer.yandex.ru/informer/33823419/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
        style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:33823419,lang:'ru'});return false}catch(e){}" /></a>
        <!-- /Yandex.Metrika informer -->

        <!-- Yandex.Metrika counter --><script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter34664390 = new Ya.Metrika({ id:34664390, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/34664390" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
      </span>
      <span class="footer__meta__item">
        <a href="http://www.pd-s.ru">Сделано в "Дизайн-проект"</a>
      </span>
    </p>
  </div>
</footer>
<script src="{% static 'js/main.js' %}"></script>
{% block extra_js %}
{% endblock %}
</body>
</html>

app/app/templates/forms.html
{{form.non_field_errors}}
{% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}">{{field.label}}<span>{{field.errors}}</span></label>
    {{field}}
  </div>
{% endfor %}

app/app/templates/layout.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block layout %}

  <div class="container">
    <div class="row row-offcanvas row-offcanvas-left">
      <div class="sidebar-offcanvas col-xs-2 col-sm-1 col-md-1" role="navigation" id="sidebar">
        <div class="well sidebar-nav text-center">
          {% block side_menu %}
            {% include 'side_menu.html' %}

          {% endblock %}
        </div>
      </div>
      <div class="col-xs-12 col-md-10 col-sm-10">
        <p class="visible-xs offcanvas-toggle">
          <button type="button" class="btn btn-primary btn-xs js-offcanvas-btn" data-toggle="offcanvas">Показать меню
          </button>
        </p>
        <div class="row clear real-content">
          <div class="col-sm-12">
            {% block breadcrumbs %}{% endblock %}
            {% block title %}{% endblock %}
            {% block content %}
              Not found
            {% endblock %}
          </div>
        </div>
        <!-- <hr /> -->
      </div>
    </div>
  </div>
{% endblock %}

app/app/templates/side_menu.html
{% load staticfiles %}
<ul class="nav row">
  <li class="col-xs-12 sidebar-nav__item{% if location == 'auction' %} active {% endif %}">
    <a href="{% url 'auction:lot_list' %}">
      <img src="{% static 'img/lots.png' %}">
      <p>ТОРГИ</p>
    </a>
  </li>
  <li class="col-xs-12 sidebar-nav__item {% if location == 'favorite' %} active {% endif %}">
    <a href="{% url 'auction:favorite_list' %}">
      <img src="{% static 'img/favorits.png' %}">
      <p>ИЗБРАННОЕ</p>
    </a>
  </li>
  <li class="col-xs-12 sidebar-nav__item {% if location == 'auction_monitoring' %} active {% endif %}">
    <a href="{% url 'auction:monitoring' %}">
      <img src="{% static 'img/monitoring.png' %}">

      <p>МОНИТОРИНГ</p>
    </a>
  </li>
  <li class="col-xs-12 sidebar-nav__item {% if request.path == '/calendar/' %} active {% endif %}">
    <a href="{% url 'auction:calendar' %}">
      <img src="{% static 'img/calendar.png' %}">

      <p>КАЛЕНДАРЬ</p>
    </a>
  </li>
  <li class="col-xs-12 sidebar-nav__item {% if request.path == 'auction/question/' %} active {% endif %}">
    <a href="{% url 'auction:question_form' %}">
      <img src="{% static 'img/yurist.png' %}">

      <p>ВОПРОС ЮРИСТУ</p>
    </a>
  </li>
<!--{#   <li class="col-xs-12 sidebar-nav__item {% if request.path == '/analitic/' %} active {% endif %}">
    <a href="{% url 'analitic' %}">
      <img src="{% static 'img/analytics.png' %}">

      <p>АНАЛИТИКА</p>
    </a>
  </li>
  <li class="col-xs-12 sidebar-nav__item {% if request.path == '/secretary/' %} active {% endif %}">
    <a href="{% url 'secretary' %}">
      <img src="{% static 'img/secretary.png' %}">

      <p>СЕКРЕТАРЬ</p>
    </a>
  </li> #}-->
  <!--<li class="col-xs-12 sidebar-nav__item {% if request.path == '/price/' %} active {% endif %}">-->
    <!--<a href="{% url 'auction:lot_list' %}">-->
      <!--<img src="{% static 'img/menu_8.png' %}">-->

      <!--<p>Настройки</p>-->
    <!--</a>-->
  <!--</li>-->
</ul>