app/app/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='static_pages/index.html'), name='index'),
    url(r'^auction/', include('auction.urls', namespace='auction')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^auc_accounts/', include('auc_accounts.urls', namespace='auc_accounts')),
    url(r'^forums/', include('forums.urls', namespace='forums')),
    url(r'^admin/', include(admin.site.urls)),
    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='static_pages/about.html'), name='about'),
    url(r'^services/$', TemplateView.as_view(template_name='static_pages/services.html'), name='services'),
    url(r'^partners/$', TemplateView.as_view(template_name='static_pages/partners.html'), name='partners'),
    url(r'^bankruptcy/$', TemplateView.as_view(template_name='static_pages/bankruptcy.html'), name='bankruptcy'),
    url(r'^analitic/$', TemplateView.as_view(template_name='static_pages/analitic.html'), name='analitic'),
    url(r'^contacts/$', TemplateView.as_view(template_name='static_pages/contacts.html'), name='contacts'),
    url(r'^rules/$', TemplateView.as_view(template_name='static_pages/rules.html'), name='rules'),
    url(r'^price/$', TemplateView.as_view(template_name='static_pages/price.html'), name='price'),
    url(r'^secretary/$', TemplateView.as_view(template_name='static_pages/secretary.html'), name='secretary'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forums/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from forums.views import CategoryListView, ForumDetailView, TopicDetailView, TopicCreateView, PostCreateView


urlpatterns = patterns('',
    url(r'^$', CategoryListView.as_view(), name='overview'),
    url(r'^(?P<pk>\d+)/$', ForumDetailView.as_view(), name='forum'),
    url(r'^(?P<forum_id>\d+)/create/$', login_required(TopicCreateView.as_view()), name='topic_create'),
    url(r'^topic/(?P<pk>\d+)/$', TopicDetailView.as_view(), name='topic'),
    url(r'^topic/(?P<pk>\d+)/create/$', login_required(PostCreateView.as_view()), name='post_create'),
)

app/forums/models.py
from django.conf import settings
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(_("Name"), max_length=255, unique=True)
    position = models.IntegerField(_("Position"), default=0)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Forum(models.Model):
    category = models.ForeignKey(Category, related_name='forums')
    name = models.CharField(_("Name"), max_length=255)
    position = models.IntegerField(_("Position"), default=0)
    description = models.TextField(_("Description"), blank=True)
    is_closed = models.BooleanField(_("Is closed"), default=False)

    class Meta:
        ordering = ['position']

    def get_latest_topic(self):
        if self.topics.count() > 0:
            return self.topics.all()[0]
        return None

    def get_latest_poster(self):
        latest_topic = self.get_latest_topic()
        if latest_topic:
            return latest_topic.last_post.user.username
        return '-'

    def count_topics(self):
        return self.topics.count()

    def count_posts(self):
        count = 0
        for topic in self.topics.all():
            count += topic.count_posts()
        return count

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Topic(models.Model):
    forum = models.ForeignKey(Forum, related_name='topics')
    name = models.CharField(_("Name"), max_length=255)
    last_post = models.ForeignKey('Post', verbose_name=_("Last post"), related_name='forum_last_post', blank=True, null=True)

    class Meta:
        ordering = ['-last_post__created']

    def count_posts(self):
        return self.posts.count()

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    topic = models.ForeignKey(Topic, related_name='posts')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='forum_posts')
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    updated = models.DateTimeField(_("Updated"), auto_now=True)
    body = models.TextField(_("Body"))

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.body

app/forums/forms.py
from django import forms


class TopicCreateForm(forms.Form):
    topic = forms.CharField(label="Topic", min_length=3)
    message = forms.CharField(label="Message", min_length=3, widget=forms.Textarea())


class PostCreateForm(forms.Form):
    message = forms.CharField(label="Message", min_length=3, widget=forms.Textarea())

app/forums/views.py
from django.views.generic import ListView, DetailView, FormView
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

from forums.forms import TopicCreateForm, PostCreateForm
from forums.models import Category, Topic, Forum, Post


class CategoryListView(ListView):
    model = Category


class ForumDetailView(DetailView):
    model = Forum


class TopicDetailView(DetailView):
    model = Topic


class TopicCreateView(FormView):
    template_name = 'forums/topic_create.html'
    form_class = TopicCreateForm

    def dispatch(self, request, *args, **kwargs):
        self.forum = Forum.objects.get(id=kwargs.get('forum_id', None))
        if self.forum.is_closed and not request.user.is_staff:
            messages.error(request, _("You do not have the permissions to create a topic."))
            return HttpResponseRedirect(reverse_lazy('forums:forum', args=[self.forum.id]))
        return super(TopicCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        topic_name = form.cleaned_data['topic']
        post_body = form.cleaned_data['message']
        user = self.request.user

        topic = Topic(forum=self.forum, name=topic_name)
        topic.save()
        post = Post(topic=topic, body=post_body, user=user)
        post.save()
        topic.last_post = post
        topic.save()

        self.success_url = reverse('forums:topic', args=[topic.id])

        return super(TopicCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(TopicCreateView, self).get_context_data(**kwargs)
        context['forum'] = Forum.objects.get(id=self.kwargs.get('forum_id', None))
        return context


class PostCreateView(FormView):
    template_name = 'forums/post_create.html'
    form_class = PostCreateForm

    def dispatch(self, request, *args, **kwargs):
        self.topic = Topic.objects.get(id=kwargs.get('pk', None))
        if self.topic.forum.is_closed and not request.user.is_staff:
            messages.error(request, _("You do not have the permissions to create a topic."))
            return HttpResponseRedirect(reverse_lazy('forums:forum', args=[self.topic.forum.id]))
        return super(PostCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        body = form.cleaned_data['message']
        user = self.request.user

        post = Post(topic=self.topic, body=body, user=user)
        post.save()
        post.topic.last_post = post
        post.topic.save()

        self.success_url = reverse('forums:topic', args=[self.topic.id])

        return super(PostCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PostCreateView, self).get_context_data(**kwargs)
        context['topic'] = Topic.objects.get(id=self.kwargs.get('pk', None))
        return context

app/app/templates/forums/category_list.html
{% extends "layout.html" %}

{% load staticfiles %}
{% load i18n %}

{% block title %}
  <h1>{% trans "Forums" %}</h1>
{% endblock %}

{% block content %}
  {% for category in category_list %}
    <h3>{{ category.name }}</h3>

    <ul class="nav nav-pills nav-stacked" role="tablist">
      {% for forum in category.forums.all %}
        <li role="presentation">
          <a href="{% url 'forums:forum' forum.id %}">{{ forum.name }}
            <span class="badge">{{ forum.count_topics }}</span>
          </a>
        </li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endblock %}

app/app/templates/forums/forum_detail.html
{% extends "layout.html" %}
{% load staticfiles i18n %}

{% block breadcrumbs %}
<ol class="breadcrumb">
  <li><a href="{% url 'forums:overview' %}">{% trans "Forums" %}</a></li>
  <li><a href="{% url 'forums:overview' %}#{{forum.category.id}}">{{forum.category.name}}</a> </li>
  <li class="active">{{forum.name}}</li>
</ol>
{% endblock %}

{% block content %}
  <h3>{{ forum.name }}</h3>

  <div class="row">
    <div class="col-sm-6">
      <ul class="nav nav-pills nav-stacked" role="tablist">
        {% for topic in forum.topics.all %}
          <li role="presentation">
            <a href="{% url 'forums:topic' topic.id %}">{{ topic.name }}
              <span class="badge">{{ topic.count_posts }}</span></a>
          </li>
        {% empty %}
          {% if forum.is_closed %}
            <p>{% trans "No topics in this forum, only admins can create and post here." %}</p>
          {% else %}
            <p>{% trans "No topics in this forum, create one :)" %}</p>
          {% endif %}
        {% endfor %}

      </ul>
      {% if not forum.is_closed or user.is_staff %}
        <p><a href="{% url 'forums:topic_create' forum.id %}" class="btn btn-primary">{% trans "Create topic" %}</a></p>
      {% endif %}

    </div>
  </div>
{% endblock %}

app/app/templates/forums/post_create.html
{% extends "layout.html" %}

{% load i18n %}

{% block breadcrumbs %}
<ol class="breadcrumb">
  <li><a href="{% url 'forums:overview' %}">{% trans "Forums" %}</a></li>
  <li><a href="{% url 'forums:overview' %}#{{topic.forum.category.id}}">{{topic.forum.category.name}}</a></li>
  <li><a href="{% url 'forums:forum' topic.forum.id %}">{{topic.forum.name}}</a></li>
  <li><a href="{% url 'forums:topic' topic.id %}">{{topic.name}}</a></li>
  <li class="active">{% trans "Create post" %}</li>
</ol>
{% endblock %}

{% block content %}
  <div class="page-header">
    <h1>{% trans "Forums" %}</h1>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div>
        <p>{{ user.first_name }} {{ user.last_name }}</p>
      </div>
    </div>
    <div class="col-md-9">
      <form method="post" action="{% url 'forums:post_create' topic.id %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_message">Сообщение<span></span></label>
          <textarea cols="40" id="id_message" class="form-control" name="message" rows="10"></textarea>
        </div>
        <p><input type="submit" class="btn btn-primary" value="{% trans "Create post" %}"></p>
      </form>
    </div>
  </div>
{% endblock %}

app/app/templates/forums/topic_create.html
{% extends "layout.html" %}

{% load i18n %}

{% block breadcrumbs %}
<ol class="breadcrumb">
  <li><a href="{% url 'forums:overview' %}">{% trans "Forums" %}</a></li>
  <li><a href="{% url 'forums:overview' %}#{{forum.category.id}}">{{forum.category.name}}</a> </li>
  <li><a href="{% url 'forums:forum' forum.id %}">{{forum.name}}</a></li>
  <li class="active">{% trans "Create topic" %}</li>
</ol>
{% endblock %}

{% block content %}
  <div class="page-header">
    <h1>{% trans "Forums" %}</h1>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div>
        <p>{{ user.first_name }} {{ user.last_name }}</p>
      </div>
    </div>
    <div class="col-md-9">
      <form method="post" action="{% url 'forums:topic_create' forum.id %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_topic">Тема<span></span></label>
          <input id="id_topic" class="form-control" name="topic" type="text">
        </div>
        <div class="form-group">
          <label for="id_message">Сообщение<span></span></label>
          <textarea cols="40" id="id_message" class="form-control" name="message" rows="10"></textarea>
        </div>
        <p><input type="submit" class="btn btn-primary" value="{% trans "Create topic" %}"></p>
      </form>
    </div>
  </div>
{% endblock %}

app/app/templates/forums/topic_detail.html
{% extends "layout.html" %}
{% load staticfiles i18n %}

{% block breadcrumbs %}
  <ol class="breadcrumb">
    <li><a href="{% url 'forums:overview' %}">{% trans "Forums" %}</a></li>
    <li><a href="{% url 'forums:overview' %}#{{ topic.forum.category.id }}">{{ topic.forum.category.name }}</a></li>
    <li><a href="{% url 'forums:forum' topic.forum.id %}">{{ topic.forum.name }}</a></li>
    <li class="active">{{ topic.name }}</li>
  </ol>
{% endblock %}

{% block content %}
  <div class="page-header">
    <h1>{% trans "Forums" %}</h1>
  </div>
  <div class="row blog_question">
    {% for post in topic.posts.all %}
      <div class="col-sm-12">
        <div class="row{% if forloop.counter == 1 %} blog_question__question{% endif %}">
          <div class="col-sm-3">
            <div class="author">
              <h4>{{ post.user.first_name }} {{ post.user.last_name }}</h4>

              <p>{{ post.created|date:"d.m.y" }}</p>
            </div>
          </div>
          <div class="col-sm-9">
            {{ post.body|linebreaks }}
          </div>

        </div>
      </div>
    {% endfor %}
  </div>

  <div class="row">
    <div class="col-sm-12">
      <div class="span12">
        {% if not topic.forum.is_closed or user.is_staff %}
          <p><a href="{% url 'forums:post_create' topic.id %}" class="btn btn-primary">{% trans "Add answer" %}</a></p>
        {% else %}
          <p>{% trans "This forum is closed, only admins can create and post here." %}
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}