app/app/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='static_pages/index.html'), name='index'),
    url(r'^auction/', include('auction.urls', namespace='auction')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^auc_accounts/', include('auc_accounts.urls', namespace='auc_accounts')),
    url(r'^forums/', include('forums.urls', namespace='forums')),
    url(r'^admin/', include(admin.site.urls)),
    # static pages
    url(r'^about/$', TemplateView.as_view(template_name='static_pages/about.html'), name='about'),
    url(r'^services/$', TemplateView.as_view(template_name='static_pages/services.html'), name='services'),
    url(r'^partners/$', TemplateView.as_view(template_name='static_pages/partners.html'), name='partners'),
    url(r'^bankruptcy/$', TemplateView.as_view(template_name='static_pages/bankruptcy.html'), name='bankruptcy'),
    url(r'^analitic/$', TemplateView.as_view(template_name='static_pages/analitic.html'), name='analitic'),
    url(r'^contacts/$', TemplateView.as_view(template_name='static_pages/contacts.html'), name='contacts'),
    url(r'^rules/$', TemplateView.as_view(template_name='static_pages/rules.html'), name='rules'),
    url(r'^price/$', TemplateView.as_view(template_name='static_pages/price.html'), name='price'),
    url(r'^secretary/$', TemplateView.as_view(template_name='static_pages/secretary.html'), name='secretary'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/auction/urls.py
from django.conf.urls import patterns, url
from auction.views import *

urlpatterns = patterns(
    '',
    url(r'^$', lot_list, name='lot_list'),
    url(r'^favorite/(?P<id>\d+)/$', favorite_list, name='favorite_list'),
    url(r'^favorite/$', favorite_list, name='favorite_list'),
    url(r'^(?P<pk>\d+)/$', lot_details, name='lot_details'),
    url(r'^mark_read/(?P<lot_id>\d+)/$', toggle_lot_read_ajax, name='mark_read'),
    url(r'^read_all/$', read_all, name='read_all'),
    url(r'^add_chapter$', add_chapter, name='add_chapter'),
    url(r'^del_chapter/(?P<id>\d+)$', del_chapter, name='del_chapter'),
    url(r'^get_comment/(?P<lot_id>\d+)/$', get_comment, name='get_comment'),
    url(r'^set_comment/(?P<lot_id>\d+)/$', set_comment, name='set_comment'),
    url(r'^add_to_chapter/$', add_to_chapter, name='add_to_chapter'),
    url(r'^remove_from_chapter/$', remove_from_chapter, name='remove_from_chapter'),
    url(r'^calendar/$', calendar, name='calendar'),
    url(r'^data_by_month/(?P<year>\d+)/(?P<month>\d+)/$', data_by_month, name='data_by_month'),
    url(r'^monitoring/$', monitoring, name='monitoring'),
    url(r'^monitoring/filter/$', filter_edit, name='filter_add'),
    url(r'^monitoring/filter/(?P<filter_id>\d+)/$', filter_edit, name='filter_edit'),
    url(r'^question/$', question_form, name='question_form'),

    # blog
    url(r'^blog/$', blog, name='blog'),
    url(r'^blog/blog_theme$', blog_theme, name='blog_theme'),
    url(r'^blog/blog_theme/blog_question$', blog_question, name='blog_question'),
)

app/auc_accounts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.utils import timezone


class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, verbose_name=_('user'))
    email_subscribe = models.BooleanField(default=False, blank=True, verbose_name=_('email subscribe'))
    organization = models.BooleanField(default=False, blank=True, verbose_name=_('organization'))
    phone = models.CharField(max_length=200, verbose_name=_('phone'))
    city = models.CharField(max_length=200, verbose_name=_('city'), default='')
    ogrn = models.CharField(max_length=200, verbose_name=_('OGRN'), default='')
    premium_expiration_date = models.DateTimeField(default=timezone.now, verbose_name=_('Premium expiration date'))
    verified = models.BooleanField(default=False, blank=True, verbose_name=_('verified'))
    sms_token = models.IntegerField(verbose_name=_('sms token'), default=0)

    def is_premium(self):
        return self.verified and self.premium_expiration_date > timezone.now()

    def __str__(self):
        return self.user.username


class Order(models.Model):
    user = models.ForeignKey(User)
    create_date = models.DateTimeField(default=timezone.now, verbose_name=_('Order create date'))
    purchase_date = models.DateTimeField(null=True, default=None, verbose_name=_('Order purchase date'))
    price = models.IntegerField(verbose_name=_('price'), default=0)
    status = models.BooleanField(default=False, blank=True, verbose_name=_('purchased'))
    months = models.IntegerField(verbose_name=_('period'), default=0)

    def __str__(self):
        return '{} {}'.format(self.user.username, self.price)


class CbRequest(models.Model):
    request = models.TextField()
    create_date = models.DateTimeField(default=timezone.now, verbose_name=_('Order create date'))

    def __str__(self):
        return str(self.create_date)

app/auction/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.db.models import Max
from django.conf import settings

class LotType(models.Model):
    title = models.CharField(max_length=200, null=True, unique=True, verbose_name=_('title'))
    code = models.CharField(max_length=200, null=True, verbose_name=_('code'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('lot type')
        verbose_name_plural = _('lot types')


class Trustee(models.Model):
    vatin = models.CharField(max_length=200, null=True,
                             verbose_name=_('vatin'))
    name = models.CharField(max_length=200, null=True, verbose_name=_('name'))
    fed_url = models.URLField(verbose_name=_('fed url'), null=True,
                              unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('trustee')
        verbose_name_plural = _('trustees')


class LotMessage(models.Model):
    lot = models.ForeignKey('Lot', null=True, verbose_name=_('lot'))
    title = models.CharField(max_length=200, null=True,
                             verbose_name=_('title'))
    date = models.DateTimeField(verbose_name=_('date'), null=True)
    fed_url = models.URLField(verbose_name=_('source'), null=True, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('lot message')
        verbose_name_plural = _('lot messages')


class DebtorMessage(models.Model):
    debtor = models.ForeignKey('Debtor', null=True, verbose_name=_('debtor'))
    title = models.CharField(max_length=200, null=True,
                             verbose_name=_('title'))
    date = models.DateTimeField(verbose_name=_('date'), null=True)
    fed_url = models.URLField(verbose_name=_('source'), null=True, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('debtor message')
        verbose_name_plural = _('debtor messages')


class Region(models.Model):
    title = models.CharField(max_length=200, null=True,
                             verbose_name=_('title'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('region')
        verbose_name_plural = _('regions')


class Debtor(models.Model):
    title = models.CharField(max_length=300, null=True,
                             verbose_name=_('title'), unique=True)
    region = models.ForeignKey('Region', null=True, verbose_name=_('region'))
    vatin = models.CharField(max_length=20, null=True, verbose_name=_('vatin'))
    register_id = models.CharField(max_length=200, null=True,
                                   verbose_name=_('register id'))
    address = models.CharField(max_length=500, null=True,
                               verbose_name=_('address'))
    fed_url = models.URLField(verbose_name=_('fed url'), null=True,
                              unique=True)

    class Meta:
        verbose_name = _('debtor')
        verbose_name_plural = _('debtors')

    def __str__(self):
        return self.title


class Organizer(models.Model):
    vatin = models.CharField(max_length=200, null=True,
                             verbose_name=_('vatin'))
    name = models.CharField(max_length=200, null=True, verbose_name=_('name'))
    fed_url = models.URLField(verbose_name=_('fed url'), null=True,
                              unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('organizer')
        verbose_name_plural = _('organizers')


class Marketplace(models.Model):
    title = models.CharField(max_length=200, null=True,
                             verbose_name=_('title'), unique=True)
    url = models.URLField(verbose_name=_('url'), null=True)
    img = models.ImageField(null=True, verbose_name=_('image'))
    fed_url = models.URLField(verbose_name=_('fed url'), null=True,
                              unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('marketplace')
        verbose_name_plural = _('marketplaces')


class Currency(models.Model):
    title = models.CharField(max_length=200, null=True,
                             verbose_name=_('title'))
    sign = models.CharField(max_length=4, null=True, verbose_name=_('sign'))

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = _('currency')
        verbose_name_plural = _('currencies')


class Status(models.Model):
    title = models.CharField(max_length=200, null=True,
                             verbose_name=_('title'))

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = _('status')
        verbose_name_plural = _('statuses')


class UserData(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, verbose_name=_('user'))
    lot = models.ForeignKey('Lot', null=True, verbose_name=_('lot'))
    comment = models.TextField(null=True, verbose_name=_('comment'))
    read = models.BooleanField(default=False, verbose_name=_('read'))
    sent = models.BooleanField(default=False, verbose_name=_('sent'))
    chapter = models.ForeignKey('Chapter', null=True, verbose_name=_('chapter'))

    def __str__(self):
        return '{} {}'.format(self.user, self.lot)

    class Meta:
        verbose_name = _('user data')
        verbose_name_plural = _('user data')


class Chapter(models.Model):
    title = models.CharField(max_length=200, null=True,
                             verbose_name=_('title'))
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, verbose_name=_('user'))

    def __str__(self):
        return self.title

    def get_lot_count(self, user_id):
        return Lot.objects.filter(users_data=user_id,
                                  userdata__chapter_id=self.id).count()

    class Meta:
        verbose_name = _('chapter')
        verbose_name_plural = _('chapters')


class Lot(models.Model):
    active = models.BooleanField(default=False, verbose_name=_('active'))
    number = models.CharField(max_length=200, verbose_name=_('number'),
                              null=True, unique=True)
    marketplace = models.ForeignKey(Marketplace, null=True, verbose_name=_('marketplace'))
    fed_url = models.URLField(verbose_name=_('fed url'), null=True,
                              unique=True)
    marketplace_url = models.URLField(verbose_name=_('marketplace url'),
                                      null=True)
    description = models.TextField(verbose_name=_('description'), null=True)
    currency = models.ForeignKey(Currency, null=True, verbose_name=_('currency'))
    status = models.ForeignKey(Status, null=True)
    date_message = models.DateTimeField(verbose_name=_('placement date'),
                                        null=True)
    date_start = models.DateTimeField(verbose_name=_('trading start date'),
                                      null=True)
    date_finish = models.DateTimeField(verbose_name=_('trading finish date'),
                                       null=True)
    date_app_from = models.DateTimeField(null=True, verbose_name=_('apply date from'))
    date_app_to = models.DateTimeField(null=True, verbose_name=_('apply date to'))
    case_number = models.CharField(max_length=200, null=True, verbose_name=_('case number'))
    cort = models.CharField(max_length=200, null=True, verbose_name=_('cort'))
    debtor = models.ForeignKey(Debtor, null=True, verbose_name=_('debtor'))
    trustee = models.ForeignKey(Trustee, null=True, verbose_name=_('trustee'))
    organizer = models.ForeignKey(Organizer, null=True, verbose_name=_('organizer'))
    lot_type = models.ForeignKey(LotType, null=True, verbose_name=_('lot type'))
    price_start = models.DecimalField(max_digits=15, decimal_places=2, null=True, verbose_name=_('price start'))
    users_data = models.ManyToManyField(settings.AUTH_USER_MODEL, through='UserData', blank=True,
                                        related_name='+', verbose_name=_('user data'))

    class Meta:
        verbose_name = _('lot')
        verbose_name_plural = _('lots')

    def __str__(self):
        return self.number

    def get_absolute_url(self):
        return reverse('auction:lot_details', kwargs={'pk': self.id})

    def get_price(self):
        max_date = self.price_set.aggregate(Max('date'))['date__max']
        return self.price_set.filter(date=max_date)[0]


class Price(models.Model):
    lot = models.ForeignKey(Lot, null=True, related_name='price_set', verbose_name=_('lot'))
    value = models.DecimalField(max_digits=15, decimal_places=2, null=True, verbose_name=_('value'))
    date = models.DateTimeField(null=True, verbose_name=_('date'))

    def __str__(self):
        return str(self.value)

    class Meta:
        verbose_name = _('price')
        verbose_name_plural = _('prices')


class Document(models.Model):
    lot = models.ForeignKey(Lot, null=True, verbose_name=_('lot'))
    title = models.CharField(max_length=200, null=True,
                             verbose_name=_('title'))
    fed_url = models.URLField(verbose_name=_('url'), null=True, unique=True)
    date = models.DateTimeField(verbose_name=_('date'), null=True)

    class Meta:
        verbose_name = _('document')
        verbose_name_plural = _('documents')


class Filter(models.Model):
    def __str__(self):
        return self.title

    PERIODS = (
        (1, _('hourly')),
        (2, _('daily')),
        (3, _('weekly')),
    )
    is_active = models.BooleanField(default=False, verbose_name=_('active'))
    title = models.CharField(max_length=200, null=True, blank=False,
                             verbose_name=_('title'))
    key_words = models.TextField(max_length=100, blank=True,
                                 verbose_name=_('keywords'), null=True)

app/auction/forms.py
from django import forms
from auction.models import Marketplace, LotType, Chapter, Filter, Region, Question
from django.utils.translation import ugettext_lazy as _


class SearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label=_('search'))
    is_visited = forms.BooleanField(required=False, label=_('is visited'))
    places = forms.ModelMultipleChoiceField(queryset=Marketplace.objects.all().distinct(), required=False,
                                            label=_('places'))
    region = forms.CharField(max_length=100, required=False, label=_('region'))
    price1 = forms.CharField(max_length=100, required=False, label=_('price from'))
    price2 = forms.CharField(max_length=100, required=False, label=_('price to'))
    date1 = forms.CharField(max_length=100, required=False, label=_('date from'))
    date2 = forms.CharField(max_length=100, required=False, label=_('date to'))
    types = forms.ModelMultipleChoiceField(queryset=LotType.objects.all().distinct(), required=False,
                                           label=_('lot types'))
    debtor = forms.CharField(max_length=100, required=False, label=_('debtor'))
    trustee = forms.CharField(max_length=100, required=False, label=_('trustee'))


class AddChapterForm(forms.Form):
    title = forms.CharField(max_length=100, label=_('title'))

    def save(self, user):
        chapter = Chapter(title=self.cleaned_data.get('title'), user=user)
        chapter.save()


class FilterForm(forms.ModelForm):
    lot_types = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        queryset=LotType.objects.all(),
        required=False,
    )
    regions = forms.ModelMultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        queryset=Region.objects.all(),
        required=False,
    )

    class Meta:
        model = Filter
        exclude = ['user']


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = []

app/forums/forms.py
from django import forms


class TopicCreateForm(forms.Form):
    topic = forms.CharField(label="Topic", min_length=3)
    message = forms.CharField(label="Message", min_length=3, widget=forms.Textarea())


class PostCreateForm(forms.Form):
    message = forms.CharField(label="Message", min_length=3, widget=forms.Textarea())

app/auction/templates/auction/email_plain.html
Здравствуйте {{ user.name }}! По вашим фильтрам:
{% for filter in filters %}
  {{ filter.title }}
{% endfor %}

Лоты:

{% for lot in lots %}
  {{ lot.get_full_url }} : {{ lot.number }}
{% endfor %}

app/auction/templates/auction/favorite.html
{% extends "layout.html" %}
{% load auction_extras %}
{% load widget_tweaks %}

{% block side_menu %}
{% include 'side_menu.html' with location='favorite' %}
{% endblock %}
{% block title %}{% endblock %}
{% block content %}
  <h3>Избранное</h3>
  <div class="lot-fave">

    <div class="lot-fave__btns">
      {% for chapter in chapter_set %}
        <div class="btn btn-info lot-fave__btn">
          <a href="{% url 'auction:favorite_list' id=chapter.id %}">
            {{ chapter.title }}
            <span class="badge">{% get_chapters_lot_count user_id=user.id chapter_id=chapter.id %}</span>
        </a>
        <!-- Link to remove chapter -->
        <a href="{% url 'auction:del_chapter' id=chapter.id %}">
            <i class="fa fa-times lot-fave__remove"></i>
        </a>
        </div>
      {% endfor %}
      <div class="lot-fave__btn--add btn-warning btn-xs btn">Добавить раздел</div>
    </div>
  </div>

  <!-- Add fave modal -->
  <div class="modal fade" id="lot-fave__modal-add">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
              aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Добавить раздел</h4>
        </div>
        <form action="{% url 'auction:add_chapter' %}" class="lot-fave__add-form" method="POST">
            {% csrf_token %} 
          <div class="modal-body">

            <div class="form-group">
              {{ add_form.title|add_class:'form-control' }}
            </div>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
            <input type="submit" class="btn btn-primary lot-fave__add-form-btn" value="Добавить">
          </div>
        </form>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div><!-- /.modal -->
  <!-- end Add fave modal -->


  {% lot_list %}
{% endblock %}

app/auction/templates/auction/lot_list.html
{% load auction_extras staticfiles %}
{% for lot in lot_set %}
{% with lot.userdata_set.all|first as userdata %}
<div class="panel panel-default reset auction-1 js-auction-1" data-auction-id="{{ lot.id }}">
  <!-- Comment modal -->
  <div class="modal fade commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel"
       aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
              aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Оставить комментарий</h4>
        </div>
        <form class="auction-s__form_comment" action="#">
          {% csrf_token %}
          <div class="modal-body">

            <div class="form-group">
              <label class="control-label" for="comment-modal">Введите комментарий</label>
              <textarea class="form-control comment-text-modal" name="comment">{{ userdata.comment }}</textarea>
            </div>
          </div>
          <div class="modal-footer">
            <input type="submit" class="btn btn-primary commentModal__tgigger-comment" value="Комментировать"/>
            <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <!-- end Comment modal -->
  <div class="panel-heading clearfix">
    <ul class="pull-left auction-1__heading">
      <li class="active need-auth">
        <a href="{{ lot.get_absolute_url }}">Лот № {% hide_text user=user lot=lot str=lot.number %} </a>
      </li>
      <li class="clear visible-xs"></li>
      <li>
        {% if lot.price_start < MAX_PRICE_FOR_GUESTS or user.userprofile.is_premium %}
          <a class="auction-1__mt" href="{{ lot.marketplace_url }}" target="_blank">{{ lot.marketplace.title }}</a>
        {% else %}
          {% hide_text user=user lot=lot str=lot.marketplace.title %}
        {% endif %}
      </li>
      <li>
        <img class="auction-1__logo" src="
              {% if lot.marketplace.img %}{{ MEDIA_URL }}{{ lot.marketplace.img }}{% else %}{% static 'img/auction.png' %}{% endif %}">
      </li>
    </ul>
    <menu class="btn-group m0 right auction-1__btns" role="group">
      {% if user.is_authenticated %}

      <button data-href="{% url 'auction:mark_read' lot_id=lot.id %}"
              class="btn
                    btn-default 
                    btn-xs 
                    js-auction-1-btn-remove
                    {% if userdata.read %}
                    auction-1__btn--active
                    {% endif %}">
        <i class="fa fa-times fa-2x default-label-margin"></i>
      </button>
      <!-- Fave button -->
      {% get_chapter user.id lot.id as chapter %}
      <div class="btn-group
                  js-auction-1__fave-btn 
                  {% if chapter %}
                  auction-1--fave-active 
                  {% endif %}"
           role="group">
        <button class="btn
                btn-default 
                btn-xs 
                dropdown-toggle 
                {% if chapter %}
                auction-1__btn--active
                {% endif %}" data-toggle="dropdown">
          <i class="fa fa fa-star-o fa-2x default-label-margin"></i>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li role="presentation" class="dropdown-header">Мои разделы</li>
          {% if chapter %}
          <li class="dropdown-alert js-auction-1__remove-fave">
            <a href="#">
              <i class="fa fa-times-circle-o"></i>
              Удалить
            </a>
          </li>
          {% endif %}

          {% for chapter in chapter_set %}
          <li class="auction-1__add-fave" data-category-id="{{ chapter.id }}">
            <a href="#">{{ chapter.title }}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
      <!-- // Fave button -->

      <button class="btn
                     btn-default 
                     btn-xs 
                     js-auction-1__add-comment
                     {% if userdata.comment %}
                     auction-1__btn--active
                     {% endif %}
                     "
              data-get-url="{% url 'auction:get_comment' lot_id=lot.id %}"
              data-set-url="{% url 'auction:set_comment' lot_id=lot.id %}">
        <i class="fa fa-comment-o fa-2x default-label-margin"></i>
      </button>

      {% endif %}
      <button class="btn
                    btn-default 
                    btn-xs
                    ">
        <i class="fa fa-arrows-alt fa-2x default-label-margin"></i>
      </button>
    </menu>

  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-10 col-sm-12">
        <p class="text-justify auction-1__desc"><a href="{{ lot.get_absolute_url }}">
          {{ lot.description|truncatewords:50 }}</a></p>
      </div>
      <div class="col-md-2 col-sm-12">
        {% if lot.lot_type.title == 'Публичное предложение' and lot.price_set.all|length > 1%}
        <div class="auction-1__price_wrap auction-1__price_wrap--down">
          <p class="">
						<span class="auction-1__price">
							{{ lot.get_price }}
							<i class="fa fa-long-arrow-down auction-1__arrow--down"></i>
						</span>

            <span class="auction-1__currency">{{ lot.currency }}</span>
          </p>
          <div class="auction-1__price-list">
            {% for price in lot.price_set.all %}
            {% if lot.price_set.all|first == price %}
                    <span class="auction-1__price">
										{{ lot.get_price }}
										<i class="fa fa-long-arrow-down auction-1__arrow--down"></i>
									</span>
            {% else %}
            <div class="auction-1__price-list-1">
              <span class="text-muted">{{ price.date }}</span>
              <b class="text-danger">{{ price.value }}</b>
            </div>
            {% endif %}
            {% endfor %}
          </div>
        </div>
        {% elif lot.lot_type.title == 'Публичное предложение' %}
        <div class="auction-1__price_wrap">
          <p class="">
								<span class="auction-1__price">
										{{ lot.price_start }}
										<i class="fa fa-long-arrow-down auction-1__arrow--down"></i>
								</span>
            <span class="auction-1__currency">{{ lot.currency }}</span>
          </p>
        </div>
        {% else %}
        <div class="auction-1__price_wrap">
          <p class="">
								<span class="auction-1__price">
										{{ lot.price_start }}
										<i class="fa fa-long-arrow-up auction-1__arrow--up"></i>
								</span>
            <span class="auction-1__currency">{{ lot.currency }}</span>
          </p>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="panel-footer auction-1__footer">
    <div class="clearfix auction-1__footer__bg">
      <div class="col-sm-12 col-md-4">
        <p>Размещено: <span class="mark">{{ lot.date_message }}</span></p>
      </div>
      <div class="col-sm-12 col-md-8 range">
        <p>Проведение торгов с {{ lot.date_start }} до {{ lot.date_finish }}</p>
      </div>
    </div>
    <div class="expanded-info no-display auction-1__footer__meta2">
      <div class="col-xs-12 auction-1__footer__bg">
        <p class="bl bl-pd clearfix">
          Должник: <span class="text-black">{% hide_text user=user lot=lot str=lot.debtor.title %}</span>
        </p>
      </div>

      <div class="form-group clearfix row-inline-block">
        <p class="need-auth">
          <span class="text-muted">ИНН:</span>
          <span class="text-black">{% hide_text user=user lot=lot str=lot.debtor.vatin %}</span>
          &nbsp;&nbsp;&nbsp;
          <span class="text-muted">ОГРН:</span>
          <span class="text-black">{% hide_text user=user lot=lot str=lot.debtor.register_id %}</span>
        </p>

        <p class="need-auth">
          <span class="text-muted">Регион:</span>
          <span class="text-black">{% hide_text user=user lot=lot str=lot.debtor.region.title %}</span>
        </p>

        <p class="need-auth">
          <span class="text-muted">Адрес:</span>
          <span class="text-black">{% hide_text user=user lot=lot str=lot.debtor.address %}</span>
        </p>
      </div>
    </div>
  </div>
</div>
{% endwith %}
{% endfor %}
{% if lot_set %}
<section class="text-center">
  <ul class="pagination pagination-centered">
    {% if lot_set.has_previous %}
    <li>
      <a href="/auction/?page={{ lot_set.previous_page_number }}{% if search %}&{{ search }}{% endif %}">Назад</a>
    </li>
    {% endif %}
    {% for p in page_range %}
    <li
    {% if p == lot_set.number %} class="active"{% endif %}>
    <a href="/auction/?page={{ p }}{% if search %}&{{ search }}{% endif %}">{{ p }}</a>
    </li>
    {% endfor %}
    <li class="disabled"><a href="#">...</a></li>
    <li>
      <a href="/auction/?page={{ lot_set.paginator.num_pages }}{% if search %}&{{ search }}{% endif %}">{{ lot_set.paginator.num_pages }}</a>
    </li>
    {% if lot_set.has_next %}
    <li>
      <a href="/auction/?page={{ lot_set.next_page_number }}{% if search %}&{{ search }}{% endif %}">Вперед</a>
    </li>
    {% endif %}
  </ul>
  <form method="get">
    {% if not search %}
    <input type="text" name="page"/>
    {% endif %}
  </form>
</section>
{% else %}
Список лотов пуст
{% endif %}